# Generated by Django 3.2 on 2021-06-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mall', '0002_alter_order_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
